[features]
seeds = false
skip-lint = false

[programs.localnet]
bbc_staking = "BBCStK1ng1111111111111111111111111111111111"

[programs.devnet]
bbc_staking = "BBCStK1ng1111111111111111111111111111111111"

[programs.mainnet]
bbc_staking = "BBCStK1ng1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"

[[test.genesis]]
address = "mWusXdRfsYAoFtYdaDcf8tmG7hnRNvnVc2TuvNEpump"
program = "spl_token.so"